// Generated by CoffeeScript 1.3.3
(function() {
  var base_url, display_dp_comment, display_tb_comment, fetch_comments, gen_dp_comment_entry, gen_tb_comment_entry, handle_comment_result, host, init_comment_box, port, show_shop_info;

  jQuery.support.cors = true;

  host = "http://localhost";

  port = "3000";

  base_url = host + ":" + port;

  fetch_comments = function(operator_id, fetch_id, platform, page) {
    var fetch_url;
    init_comment_box();
    fetch_url = base_url + "/comments?operator_id=" + operator_id + "&fetch_id=" + fetch_id + "&platform=" + platform + "&page=" + page;
    $("#current_page").val(page);
    $("#current_operator_id").val(operator_id);
    $("#current_fetch_id").val(fetch_id);
    $("#current_platform").val(platform);
    return $.get(fetch_url, function(data, textStatus) {
      $(".bar").css("width", "50%");
      handle_comment_result(fetch_id, platform, data);
      $(".bar").css("width", "80%");
      $("#current_page_size").val(data.data.length);
      $("#page_size").val(data.info.page_size);
      $(".bar").css("width", "100%");
      $(".progress").css("display", "none");
      if ($("#current_page").val() <= 1) {
        $(".previous").addClass("disabled");
      } else {
        $(".previous").removeClass("disabled");
      }
      if ($("#current_page_size").val() < $("#page_size").val()) {
        return $(".next").addClass("disabled");
      } else {
        return $(".next").removeClass("disabled");
      }
    }, 'jsonp');
  };

  init_comment_box = function() {
    $(".progress").css("display", "block");
    $(".bar").css("width", "10%");
    return $(".comment_box").html("");
  };

  handle_comment_result = function(fetch_id, platform, data) {
    switch (platform) {
      case "taobao":
        return display_tb_comment(fetch_id, data);
      case "dianping":
        return display_dp_comment(fetch_id, data);
      default:
        return alert("unknown platform:" + platform);
    }
  };

  display_tb_comment = function(fetch_id, data) {
    var comment_entry, display_content, _i, _len, _ref;
    display_content = "";
    _ref = data.data;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      comment_entry = _ref[_i];
      display_content += gen_tb_comment_entry(fetch_id, comment_entry);
    }
    return $(".comment_box").html(display_content);
  };

  gen_tb_comment_entry = function(fetch_id, comment_entry) {
    var comment_result;
    comment_result = '<hr>\
       <div class="comment-content row">\
           <div class="span2">\
               <p><a href="' + comment_entry['userLink'] + '" target="_blank">' + comment_entry['nick'] + '</a></p>\
               <p><img src="' + comment_entry['userCreditImg'] + '"></p>\
               <p>Vip：' + comment_entry['userVipLevel'] + '</p>\
           </div>\
           <div class="comment-rst span8">\
               <blockquote>' + comment_entry['content'] + '</blockquote>\
               <div class="comment-date">' + comment_entry['date'] + '</div>\
           </div>\
        </div>';
    return comment_result;
  };

  display_dp_comment = function(fetch_id, data) {
    var comment_entry, display_content, _i, _len, _ref;
    display_content = "";
    _ref = data.data;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      comment_entry = _ref[_i];
      display_content += gen_dp_comment_entry(fetch_id, comment_entry);
    }
    return $(".comment_box").html(display_content);
  };

  gen_dp_comment_entry = function(fetch_id, comment_entry) {
    var comment_result;
    comment_result = '<hr>\
        <div class="comment-content row">\
            <div class="span2">\
                <p><a href="http://www.dianping.com/member/' + comment_entry['user_id'] + '" target="_blank"><img src="' + comment_entry['avatar'] + '"></a></p>\
                <p>\
                    <a href="http://www.dianping.com/member/' + comment_entry['user_id'] + '" target="_blank">' + comment_entry['user_name'] + '</a>\
                </p>\
            </div>\
            <div class="comment-rst span10">\
                <div>\
                    <span>评分：' + comment_entry['comment_star'] + '颗星</span>\
                    <span>口味：' + comment_entry['flavour'] + '</span>\
                    <span>环境：' + comment_entry['environment'] + '</span>\
                    <span>服务：' + comment_entry['service'] + '</span>';
    if (comment_entry['average'] && typeof comment_entry['average'] !== void 0) {
      comment_result += '<span>人均：' + comment_entry['average'] + '</span>';
    }
    comment_result += '\
                </div>\
                <div class="comment-entry">\
                    <span class="cateComment">' + (comment_entry['comment_type'] || "") + '</span>\
                    <blockquote>' + comment_entry['comment_content'] + '</blockquote>\
                    <div class="more">\
                        <a href="http://www.dianping.com/review/' + fetch_id + '" target="_blank">全文</a>\
                    </div>\
                    <div class="time">' + comment_entry['comment_time'] + '</div>\
                </div>\
            </div>\
        </div>';
    return comment_result;
  };

  $(".previous").click(function(e) {
    var current_fetch_id, current_operator_id, current_page, current_page_size, current_platform, page_size;
    current_page = $("#current_page").val();
    current_page_size = $("#current_page_size").val();
    page_size = $("#page_size").val();
    current_operator_id = $("#current_operator_id").val();
    current_fetch_id = $("#current_fetch_id").val();
    current_platform = $("#current_platform").val();
    if (current_page <= 1) {
      return false;
    }
    return fetch_comments(current_operator_id, current_fetch_id, current_platform, --current_page);
  });

  $(".next").click(function(e) {
    var current_fetch_id, current_operator_id, current_page, current_page_size, current_platform, page_size;
    current_page = $("#current_page").val();
    current_page_size = $("#current_page_size").val();
    page_size = $("#page_size").val();
    current_operator_id = $("#current_operator_id").val();
    current_fetch_id = $("#current_fetch_id").val();
    current_platform = $("#current_platform").val();
    if (current_page_size < page_size) {
      return false;
    }
    return fetch_comments(current_operator_id, current_fetch_id, current_platform, ++current_page);
  });

  $(".typeahead").typeahead({
    source: function(typeahead, query) {
      var platform, url;
      host = "http://localhost";
      port = "3000";
      base_url = host + ":" + port;
      platform = $("#current_platform").val();
      url = base_url + "/products?platform=" + platform + "&title=" + query;
      return $.ajax({
        url: url,
        method: 'GET',
        dataType: "jsonp",
        success: function(data) {
          return typeahead.process(data);
        }
      });
    },
    property: "title",
    items: 15,
    onselect: function(obj) {
      var platform;
      $(".progress").css("display", 'block');
      platform = $("#current_platform").val();
      show_shop_info(platform, obj);
      return fetch_comments(obj.operator_id, obj.fetch_id, platform, 1);
    },
    timeout: $("#current_platform").val() === "dianping" ? 800 : 400
  });

  show_shop_info = function(platform, obj) {
    var shop_info, shop_url;
    shop_info = "";
    shop_url = "";
    if (platform === "dianping") {
      shop_url = "http://www.dianping.com/shop/" + obj.fetch_id;
      shop_info = "<dl class='detail'>                <dt>店铺信息</dt>                <dd class='shopname'><a href='" + shop_url + "'>" + $("#search_product").val() + "</a></dd>                <dd class='address'><strong>地址：</strong>" + obj.address + "</dd>                <dd class='rate'>评分：" + obj.rate + "颗星</dd>                <dd class='average'>人均：￥" + obj.average + "</dd></dl>";
    } else if (platform === "taobao") {
      shop_info = "<dl class='detail'>                <dt>产品信息</dt>                <dd class='shopname'><a href='" + obj.href + "'>" + $("#search_product").val() + "</a></dd>                <dd class='sales_amount'>销售：" + obj.sales_amount + "件</dd>                <dd class='rate'>评分：" + obj.rate + "</dd>            </dl>";
    }
    return $("#shop_info_box").html(shop_info);
  };

  $("#platform_menu .dropdown-menu li").click(function() {
    var platform, platform_anchor, platform_text;
    $("#search_product").removeAttr("disabled");
    platform_anchor = $(this).children("a");
    platform_text = platform_anchor.text();
    platform = platform_anchor.attr('value');
    $("#platform_menu a .dropdown_select").text(platform_text);
    $("#current_platform").val(platform);
    $("#search_product").val("");
    $("#shop_info_box").html("");
    return $(".comment_box").html("");
  });

}).call(this);
